name: MiniGameWorld
main: com.minigameworld.MiniGameWorldMain
version: ${project.version}
author: worldbiomusic
website: https://github.com/MiniGameWorlds/MiniGameWorld
description: Customizable Minecraft MiniGame Framework
api-version: 1.14
depend: [wbmMC, Multiverse-Core]
softdepend: [WorldEdit, WorldGuard, AdvancedMultiLanguage, Vault]

commands:
  minigame:
    aliases: [mw]
    usage: |
      
      USAGE
      /<command>: get Menu Opener
      /<command> help: print usage
      /<command> join <title>: join a minigame
      /<command> view <title>: view a minigame
      /<command> leave: leave/unview a minigame
      /<command> list: show minigame list
      /<command> menu: open GUI menu
      /<command> party: party commands
      /<command> reload [<backup-folder>]: reload data
      /<command> backup [<backup-folder>]: backup data
      /<command> settings: setup settings.yml config
      /<command> games: setup minigame configs
      
permissions:

  # all
  minigameworld.*:
    description: Grants all permissions
    children: 
      minigameworld.menu: true
      minigameworld.signblock: true
      minigameworld.command: true
      minigameworld.play.*: true
      minigameworld.party.*: true
      minigameworld.config.*: true
      minigameworld.function-item.*: true
      
      
      
  # menu
  minigameworld.menu:
    description: Can open a GUI menu (can access play, party)
    default: true
    
    
    
  # signblock
  minigameworld.signblock:
    description: Can play minigame with sign block (can access play, party)
    default: true
  
  
  
  # command
  minigameworld.command:
    description: Can use all commands
    default: true
    
    
    
  # play
  minigameworld.play.*:
    description: Grants all play permissions
    children:
      minigameworld.play.join: true
      minigameworld.play.leave: true
      minigameworld.play.view: true
      minigameworld.play.unview: true
      minigameworld.play.list: true
      
  minigameworld.play.join:
    description: Can join a minigame
    default: true
  minigameworld.play.leave:
    description: Can leave a playing minigame
    default: true
  minigameworld.play.view:
    description: Can view a minigame
    default: true
  minigameworld.play.unview:
    description: Can leave a viewing minigame
    default: true
  minigameworld.play.list:
    description: Can print all minigame list
    default: true
  
  
  
  # party  
  minigameworld.party.*:
    description: Grants all party permissions
    children:
      minigameworld.party.invite: true
      minigameworld.party.accept: true
      minigameworld.party.ask: true
      minigameworld.party.allow: true
      minigameworld.party.leave: true
      minigameworld.party.kickvote: true
      minigameworld.party.msg: true
      minigameworld.party.list: true
      
  minigameworld.party.invite:
    description: Can invite a player
    default: true
  minigameworld.party.accept:
    description: Can accept invitation
    default: true
  minigameworld.party.ask:
    description: Can ask to join a player's party
    default: true
  minigameworld.party.allow:
    description: Can allow player to join
    default: true
  minigameworld.party.leave:
    description: Can leave a party
    default: true
  minigameworld.party.kickvote:
    description: Can kickvote a member
    default: true
  minigameworld.party.msg:
    description: Can send message to member
    default: true
  minigameworld.party.list:
    description: Can print member list
    default: true
  
  
  
  # config
  minigameworld.config.*:
    description: Grants all config permissions
    children:
      minigameworld.config.reload: true
      minigameworld.config.settings: true
      minigameworld.config.games: true
      minigameworld.config.backup: true
  
  minigameworld.config.reload:
    description: Can reload data
    default: op
  minigameworld.config.settings:
    description: Can set settings config
    default: op
  minigameworld.config.games:
    description: Can set minigame config
    default: op
  minigameworld.config.backup:
    description: Can backup data
    default: op
  
  
  
  # function item
  minigameworld.function-item.*:
    description: Grants all function item permissions
    children:
      minigameworld.function-item.menu-opener: true
      
  minigameworld.function-item.menu-opener:
    description: Can use menu opener 
    default: true
    
    
    
  # etc groups
  minigameworld.access.*:
    description: Grants all minigame access permissions
    children:
      minigameworld.signblock: true
      minigameworld.command: true
      minigameworld.menu: true
      minigameworld.function-item.*: true
    
    
    
    
    
    
    
    
    
    
    
    
    
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  