name: MiniGameWorld
main: com.minigameworld.MiniGameWorldMain
version: 1.0
author: worldbiomusic
description: Minecraft MiniGame Framework
api-version: 1.17
depend: [wbmMC]

commands:
  minigame:
    aliases: mg
    usage: |
      Usage
      /minigame join <title>
      /minigame leave
      /minigame list
      /minigame gui
      /minigame party
      /minigame reload
      /minigame settings
      /minigame minigames