name: MiniGameMaker
main: com.wbm.minigamemaker.MiniGameMakerMain
version: 1.0
author: worldbiomusic
description: worldbiomusic@gmail.com
api-version: 1.17
depend: [wbmMC]

commands:
  minigame:
    aliases: mg
    usage: |
      Usage
      /minigame join <title>
      /minigame leave
      /minigame list
      /minigame reload