name: MiniGameWorld
main: com.worldbiomusic.minigameworld.MiniGameWorldMain
version: 0.0.1
author: worldbiomusic
description: Minecraft MiniGame Framework
api-version: 1.17
depend: [wbmMC]

commands:
  minigame:
    aliases: [mg, minigame, mw]
    usage: |
      
      USAGE
      /<command> join <title>
      /<command> leave
      /<command> list
      /<command> menu
      /<command> party
      /<command> reload
      /<command> settings
      /<command> minigames