name: MiniGameWorld
main: com.worldbiomusic.minigameworld.MiniGameWorldMain
version: 0.3.0
author: worldbiomusic
website: https://github.com/MiniGameWorlds/MiniGameWorld
description: Minecraft MiniGame Framework
api-version: 1.14
depend: [wbmMC]

commands:
  minigame:
    aliases: [mw]
    usage: |
      
      USAGE
      /<command> join <title>
      /<command> leave
      /<command> list
      /<command> menu
      /<command> party
      /<command> reload
      /<command> settings
      /<command> minigames
      
permissions:
  minigameworld.*:
    description: Grants all permissions
    children: 
      minigameworld.menu: true
      minigameworld.play.*: true
      minigameworld.party.*: true
      minigameworld.config.*: true
      
  minigameworld.menu:
    description: Can open a GUI menu (can access play, party)
    default: true
    
  minigameworld.play.*:
    description: Grants all play permissions
    children:
      minigameworld.play.join: true
      minigameworld.play.leave: true
      minigameworld.play.list: true
  minigameworld.play.join:
    description: Can join a minigame
    default: true
  minigameworld.play.leave:
    description: Can leave a playing minigame
    default: true
  minigameworld.play.list:
    description: Can print all minigame list
    default: true
    
  minigameworld.party.*:
    description: Grants all party permissions
    children:
      minigameworld.party.invite: true
      minigameworld.party.accept: true
      minigameworld.party.ask: true
      minigameworld.party.allow: true
      minigameworld.party.leave: true
      minigameworld.party.kickvote: true
      minigameworld.party.msg: true
      minigameworld.party.list: true
  minigameworld.party.invite:
    description: Can invite a player
    default: true
  minigameworld.party.accept:
    description: Can accept invitation
    default: true
  minigameworld.party.ask:
    description: Can ask to join a player's party
    default: true
  minigameworld.party.allow:
    description: Can allow player to join
    default: true
  minigameworld.party.leave:
    description: Can leave a party
    default: true
  minigameworld.party.kickvote:
    description: Can kickvote a member
    default: true
  minigameworld.party.msg:
    description: Can send message to member
    default: true
  minigameworld.party.list:
    description: Can print member list
    default: true
  
  minigameworld.config.*:
    description: Grants all config permissions
    children:
      minigameworld.config.reload: true
      minigameworld.config.settings: true
      minigameworld.config.minigames: true
  
  minigameworld.config.reload:
    description: Can reload all configs
    default: op
  minigameworld.config.settings:
    description: Can set settings config
    default: op
  minigameworld.config.minigames:
    description: Can set minigame config
    default: op
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  